yarnPath: ".yarn/releases/yarn-berry.cjs"

# This declares dependencies that some modules haven't declared (their fault, this is a workaround)
packageExtensions:
    "elm-webpack-loader@*":
        dependencies:
            "temp": "*"
